"""This module defines project-level constants."""

REFUTES = "REFUTES"
NEI = "NOT ENOUGH INFO"
SUPPORTS = "SUPPORTS"
IDK = "IDK"
MISTRANSLATED = "MISTRANSLATED"
LABELS = [SUPPORTS, REFUTES, NEI]
LABELS_ALL = [SUPPORTS, REFUTES, NEI, MISTRANSLATED]
LABELS_TO_INDEX = {SUPPORTS: 0, REFUTES: 1, NEI: 2, IDK: 3, MISTRANSLATED: 4}
INDEX_TO_LABEL = {0: SUPPORTS, 1: REFUTES, 2: NEI, 3: IDK, 4: MISTRANSLATED}
